# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Onur Ozdemir/OneDrive/Masast/microp/microp.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Onur Ozdemir/OneDrive/Masast/microp/microp.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/Onur Ozdemir/OneDrive/Masast/microp/microp.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  {C:/Users/Onur Ozdemir/OneDrive/Masast/microp/microp.srcs/sources_1/new/ALU.sv}
  {C:/Users/Onur Ozdemir/OneDrive/Masast/microp/microp.srcs/sources_1/new/DataPath.sv}
  {C:/Users/Onur Ozdemir/OneDrive/Masast/microp/microp.srcs/sources_1/new/FSM.sv}
  {C:/Users/Onur Ozdemir/OneDrive/Masast/microp/microp.srcs/sources_1/new/General1x3Reg.sv}
  {C:/Users/Onur Ozdemir/OneDrive/Masast/microp/microp.srcs/sources_1/new/IR.sv}
  {C:/Users/Onur Ozdemir/OneDrive/Masast/microp/microp.srcs/sources_1/new/button_debouncer.sv}
  {C:/Users/Onur Ozdemir/OneDrive/Masast/microp/microp.srcs/sources_1/new/data_memory.sv}
  {C:/Users/Onur Ozdemir/OneDrive/Masast/microp/microp.srcs/sources_1/new/decrementer.sv}
  {C:/Users/Onur Ozdemir/OneDrive/Masast/microp/microp.srcs/sources_1/new/equal_comparator_for_unsigned_numbers.sv}
  {C:/Users/Onur Ozdemir/OneDrive/Masast/microp/microp.srcs/sources_1/new/greater_than_comparator_for_unsigned_numbers.sv}
  {C:/Users/Onur Ozdemir/OneDrive/Masast/microp/microp.srcs/sources_1/new/instruction_memory.sv}
  {C:/Users/Onur Ozdemir/OneDrive/Masast/microp/microp.srcs/sources_1/new/less_than_comparator_for_signed_numbers.sv}
  {C:/Users/Onur Ozdemir/OneDrive/Masast/microp/microp.srcs/sources_1/new/less_than_comparator_for_unsigned_numbers.sv}
  {C:/Users/Onur Ozdemir/OneDrive/Masast/microp/microp.srcs/sources_1/new/mux2_12bit.sv}
  {C:/Users/Onur Ozdemir/OneDrive/Masast/microp/microp.srcs/sources_1/new/mux2_1bit.sv}
  {C:/Users/Onur Ozdemir/OneDrive/Masast/microp/microp.srcs/sources_1/new/mux2_3bit.sv}
  {C:/Users/Onur Ozdemir/OneDrive/Masast/microp/microp.srcs/sources_1/new/mux2_4bit.sv}
  {C:/Users/Onur Ozdemir/OneDrive/Masast/microp/microp.srcs/sources_1/new/mux4_4bit.sv}
  {C:/Users/Onur Ozdemir/OneDrive/Masast/microp/microp.srcs/sources_1/new/mux8_3bit.sv}
  {C:/Users/Onur Ozdemir/OneDrive/Masast/microp/microp.srcs/sources_1/new/mux8_4bit.sv}
  {C:/Users/Onur Ozdemir/OneDrive/Masast/microp/microp.srcs/sources_1/new/register_file.sv}
  {C:/Users/Onur Ozdemir/OneDrive/Masast/microp/microp.srcs/sources_1/new/seven_segment_display.sv}
  {C:/Users/Onur Ozdemir/OneDrive/Masast/microp/microp.srcs/sources_1/new/sort_decoder.sv}
  {C:/Users/Onur Ozdemir/OneDrive/Masast/microp/microp.srcs/sources_1/new/sort_reg_4bit.sv}
  {C:/Users/Onur Ozdemir/OneDrive/Masast/microp/microp.srcs/sources_1/new/processor.sv}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top processor -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef processor.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file processor_utilization_synth.rpt -pb processor_utilization_synth.pb"
